mqtt_broker:  "broker.example.local"
mqtt_port: 8883
mqtt_topic_telemetry: "boxes/+/telemetry"
mqtt_topic_scan: "boxes/+/scan"
server_rest: "http://SERVER_IP:8000"
truck_id: "TRUCK-001"
local_db: "truck_local.db"

mqtt_ca_cert: "keys/ca/ca.crt"              # truck path
mqtt_client_cert: "keys/truck/truck_client.crt"
mqtt_client_key: "keys/truck/truck_client.key"

gps:
  source: "fixed"
  fixed_lat: 12.9716
  fixed_lon: 77.5946


# Server keys
#server_privkey_pem: "server_privkey.pem"
#server_pubkey_pem: "server_pubkey.pem"

# Truck identity
truck_privkey_pem: "keys/truck/truck_client.key"  # reuse same EC key for signing
