db_path: "sqlite:///./poc.db"
server_privkey_pem: "server_priv.pem"
server_pubkey_pem: "server_pub.pem"
jwt_secret: "replace-me-in-prod"
passkey_folder: "passkeys"
passkey_ttl_minutes: 90

root_user:
  email: "root@example.com"
  password: "Root!23"  # change this in production
